### PR TITLE
Implements expm1

### PR DESCRIPTION
**Pull request by harrysarson**
As discussed in https://github.com/josdejong/mathjs/pull/1046.

This pulls adds `Complex.expm1`. Please have a review and if you can think of any edge cases that are currently not tested I can add them in. :)

`expm1` does not support infinite values but then neither does `exp`. Once #23 is merged should be fairly simple to fix this.

### CODE REVIEW

**Comment by harrysarson** [comment]
On second thoughts lets merge as is and I can make a new pull once I work out the desired behaviour.

**Comment by infusion** [comment]
Yep that sounds good and also the implementation looks good so far, thanks!

**Comment by harrysarson** [comment]
@infusion are you happy calling out to the built in Math.expm1 function? 

image

**Comment by infusion** [comment]
For now it's okay. Let's bring the full new feature-set together and I'll read over the full lib before the next release.

**Comment by harrysarson** [comment]
It fails in a fairly nice way in that if someone was to run `Complex(6).expm1()` on an unsupported browser then they get

> TypeError: Math.expm1 is not a function
    at Complex.expm1 (/home/harry/git/complex.js/complex.js:580:20)

Which seems fairly explanatory to me.

**Pull request merged**
