### PR TITLE
Add types

### LINKED ISSUE #35: Ship Type Definitions
This library is really well made, thank you for all your hard work!

Since most packages on npm have Typescript definitions, I wanted to ask whether that would be welcome here as well. As I understand it, simply adopting ES modules and adding Typescript and might not be the best option. After all, this library tries to [keep its size down to a minimum](https://github.com/infusion/Complex.js#coding-style).

I'd love to add Typescript definitions, in whatever form you think would be best.

### PR DESCRIPTION
**Pull request by stefnotch**
Fix #35

### CODE REVIEW

**Comment by infusion** [comment]
That was quick!

**Comment by stefnotch** [comment]
I mostly autogenerated the types. This also means that I have a halfway working version of Complex.js that uses ES Modules and classes, in case you're interested.

One issue with the types is that they don't allow you to create `Complex` objects without calling the constructor. Let me know if that's an issue

**Comment by infusion** [comment]
Thanks for clarification. Calling the constructor without `new` is more a feature for us lazy folks. If there is no way to declare this in TS, we have to live with it. But thanks for your contribution! A new release is coming soon.

**Comment by stefnotch** [comment]
@infusion Sweet, thank you for your quick responses!
I made another pull request that lets you call the constructor without new, since that feature does seem to be rather useful.

**Pull request merged**
